# Generated by Django 2.2.5 on 2019-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coisa',
            name='retorno',
            field=models.CharField(choices=[('Devolvido', 'Devolvido'), ('Pendente', 'Pendente')], max_length=10),
        ),
    ]
